[phases.setup]
nixPkgs = ["php", "php82Packages.composer", "nodejs"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "vendor/bin/heroku-php-apache2 public/"